project:
  type: website
  output-dir: docs

website:
  title: "Quanyu Qian – Data Analytics Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/quanyu-qian


format:
  html:
    theme: cosmo
    css: styles.css

